### PR TITLE
File structure - Backend

### PR DESCRIPTION
**Pull request by mhmdtshref**
Should create this file structure for the express backend server:

```
  |__ src
  |     |__ router.js
  |     |__ server.js
  |     |__ app.js
  |     |__ controllers
  |     |       |__ Auth.controller.js
  |     |       |__ Student.controller.js
  |     |       |__ Question.controller.js
  |     |       |__ Choice.controller.js
  |     |       |__ Quiz.controller.js
  |     |       |__ Admin.controller.js
  |     |
  |     |__ middlewares
  |     |       |__ checkStudentAuth.middleware.js
  |     |       |__ checkAdminAuth.middleware.js
  |     |
  |     |__ validations
  |     |       |__ login.validation.js
  |     |       |__ signup.validation.js
  |     |       |__ index.js
  |     |
  |     |__ models 
  |             |__ Student.model.js
  |             |__ Question.model.js
  |             |__ Answer.model.js
  |             |__ StudentsAnswers.model.js
  |             |__ Mark.model.js
  |             |__ Admin.model.js
  |             
  |__ .eslintrc
  |__ .gitignore
  |__ package.json
  |__ package-lock.json
```

### CODE REVIEW

**Review by ameentalahmeh — COMMENTED** [review]
- Need one more model on **src/models** folder: `Activity`.
- For `admin` user we need a model: `Admin` (I think).

**Comment by mhmdtshref** [comment]
> * Need one more model on **src/models** folder: `Activity`.
> * For `admin` user we need a model: `Admin` (I think).

That's right, also we need to add a database table for the admin.

**Review by RazanTayyem — APPROVED** [review]

**Review by ghassanmas — CHANGES_REQUESTED** [review]
Just make the models and database in the same folder, also create `app` file

**Comment by mhmdtshref** [comment]
> Just make the models and database in the same folder, also create `app` file

Done Ghassan!

**Review by ghassanmas — APPROVED** [review]

**Pull request merged**
